/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as TravelRequestRouteImport } from './routes/travel-request'
import { Route as TasksRouteImport } from './routes/tasks'
import { Route as ResolvenAiRouteImport } from './routes/resolven-ai'
import { Route as ProfileRouteImport } from './routes/profile'
import { Route as PermitSystemRouteImport } from './routes/permit-system'
import { Route as NewsletterRouteImport } from './routes/newsletter'
import { Route as ModulesRouteImport } from './routes/modules'
import { Route as LoginRouteImport } from './routes/login'
import { Route as LegalHubRouteImport } from './routes/legal-hub'
import { Route as ExpenseClaimsRouteImport } from './routes/expense-claims'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as IndexRouteImport } from './routes/index'
import { Route as NewsletterArchiveRouteImport } from './routes/newsletter.archive'
import { Route as NewsletterIdRouteImport } from './routes/newsletter.$id'

const TravelRequestRoute = TravelRequestRouteImport.update({
  id: '/travel-request',
  path: '/travel-request',
  getParentRoute: () => rootRouteImport,
} as any)
const TasksRoute = TasksRouteImport.update({
  id: '/tasks',
  path: '/tasks',
  getParentRoute: () => rootRouteImport,
} as any)
const ResolvenAiRoute = ResolvenAiRouteImport.update({
  id: '/resolven-ai',
  path: '/resolven-ai',
  getParentRoute: () => rootRouteImport,
} as any)
const ProfileRoute = ProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => rootRouteImport,
} as any)
const PermitSystemRoute = PermitSystemRouteImport.update({
  id: '/permit-system',
  path: '/permit-system',
  getParentRoute: () => rootRouteImport,
} as any)
const NewsletterRoute = NewsletterRouteImport.update({
  id: '/newsletter',
  path: '/newsletter',
  getParentRoute: () => rootRouteImport,
} as any)
const ModulesRoute = ModulesRouteImport.update({
  id: '/modules',
  path: '/modules',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const LegalHubRoute = LegalHubRouteImport.update({
  id: '/legal-hub',
  path: '/legal-hub',
  getParentRoute: () => rootRouteImport,
} as any)
const ExpenseClaimsRoute = ExpenseClaimsRouteImport.update({
  id: '/expense-claims',
  path: '/expense-claims',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const NewsletterArchiveRoute = NewsletterArchiveRouteImport.update({
  id: '/archive',
  path: '/archive',
  getParentRoute: () => NewsletterRoute,
} as any)
const NewsletterIdRoute = NewsletterIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => NewsletterRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/dashboard': typeof DashboardRoute
  '/expense-claims': typeof ExpenseClaimsRoute
  '/legal-hub': typeof LegalHubRoute
  '/login': typeof LoginRoute
  '/modules': typeof ModulesRoute
  '/newsletter': typeof NewsletterRouteWithChildren
  '/permit-system': typeof PermitSystemRoute
  '/profile': typeof ProfileRoute
  '/resolven-ai': typeof ResolvenAiRoute
  '/tasks': typeof TasksRoute
  '/travel-request': typeof TravelRequestRoute
  '/newsletter/$id': typeof NewsletterIdRoute
  '/newsletter/archive': typeof NewsletterArchiveRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/dashboard': typeof DashboardRoute
  '/expense-claims': typeof ExpenseClaimsRoute
  '/legal-hub': typeof LegalHubRoute
  '/login': typeof LoginRoute
  '/modules': typeof ModulesRoute
  '/newsletter': typeof NewsletterRouteWithChildren
  '/permit-system': typeof PermitSystemRoute
  '/profile': typeof ProfileRoute
  '/resolven-ai': typeof ResolvenAiRoute
  '/tasks': typeof TasksRoute
  '/travel-request': typeof TravelRequestRoute
  '/newsletter/$id': typeof NewsletterIdRoute
  '/newsletter/archive': typeof NewsletterArchiveRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/dashboard': typeof DashboardRoute
  '/expense-claims': typeof ExpenseClaimsRoute
  '/legal-hub': typeof LegalHubRoute
  '/login': typeof LoginRoute
  '/modules': typeof ModulesRoute
  '/newsletter': typeof NewsletterRouteWithChildren
  '/permit-system': typeof PermitSystemRoute
  '/profile': typeof ProfileRoute
  '/resolven-ai': typeof ResolvenAiRoute
  '/tasks': typeof TasksRoute
  '/travel-request': typeof TravelRequestRoute
  '/newsletter/$id': typeof NewsletterIdRoute
  '/newsletter/archive': typeof NewsletterArchiveRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/dashboard'
    | '/expense-claims'
    | '/legal-hub'
    | '/login'
    | '/modules'
    | '/newsletter'
    | '/permit-system'
    | '/profile'
    | '/resolven-ai'
    | '/tasks'
    | '/travel-request'
    | '/newsletter/$id'
    | '/newsletter/archive'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/dashboard'
    | '/expense-claims'
    | '/legal-hub'
    | '/login'
    | '/modules'
    | '/newsletter'
    | '/permit-system'
    | '/profile'
    | '/resolven-ai'
    | '/tasks'
    | '/travel-request'
    | '/newsletter/$id'
    | '/newsletter/archive'
  id:
    | '__root__'
    | '/'
    | '/dashboard'
    | '/expense-claims'
    | '/legal-hub'
    | '/login'
    | '/modules'
    | '/newsletter'
    | '/permit-system'
    | '/profile'
    | '/resolven-ai'
    | '/tasks'
    | '/travel-request'
    | '/newsletter/$id'
    | '/newsletter/archive'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  DashboardRoute: typeof DashboardRoute
  ExpenseClaimsRoute: typeof ExpenseClaimsRoute
  LegalHubRoute: typeof LegalHubRoute
  LoginRoute: typeof LoginRoute
  ModulesRoute: typeof ModulesRoute
  NewsletterRoute: typeof NewsletterRouteWithChildren
  PermitSystemRoute: typeof PermitSystemRoute
  ProfileRoute: typeof ProfileRoute
  ResolvenAiRoute: typeof ResolvenAiRoute
  TasksRoute: typeof TasksRoute
  TravelRequestRoute: typeof TravelRequestRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/travel-request': {
      id: '/travel-request'
      path: '/travel-request'
      fullPath: '/travel-request'
      preLoaderRoute: typeof TravelRequestRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tasks': {
      id: '/tasks'
      path: '/tasks'
      fullPath: '/tasks'
      preLoaderRoute: typeof TasksRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/resolven-ai': {
      id: '/resolven-ai'
      path: '/resolven-ai'
      fullPath: '/resolven-ai'
      preLoaderRoute: typeof ResolvenAiRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/profile': {
      id: '/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof ProfileRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/permit-system': {
      id: '/permit-system'
      path: '/permit-system'
      fullPath: '/permit-system'
      preLoaderRoute: typeof PermitSystemRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/newsletter': {
      id: '/newsletter'
      path: '/newsletter'
      fullPath: '/newsletter'
      preLoaderRoute: typeof NewsletterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/modules': {
      id: '/modules'
      path: '/modules'
      fullPath: '/modules'
      preLoaderRoute: typeof ModulesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/legal-hub': {
      id: '/legal-hub'
      path: '/legal-hub'
      fullPath: '/legal-hub'
      preLoaderRoute: typeof LegalHubRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/expense-claims': {
      id: '/expense-claims'
      path: '/expense-claims'
      fullPath: '/expense-claims'
      preLoaderRoute: typeof ExpenseClaimsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/newsletter/archive': {
      id: '/newsletter/archive'
      path: '/archive'
      fullPath: '/newsletter/archive'
      preLoaderRoute: typeof NewsletterArchiveRouteImport
      parentRoute: typeof NewsletterRoute
    }
    '/newsletter/$id': {
      id: '/newsletter/$id'
      path: '/$id'
      fullPath: '/newsletter/$id'
      preLoaderRoute: typeof NewsletterIdRouteImport
      parentRoute: typeof NewsletterRoute
    }
  }
}

interface NewsletterRouteChildren {
  NewsletterIdRoute: typeof NewsletterIdRoute
  NewsletterArchiveRoute: typeof NewsletterArchiveRoute
}

const NewsletterRouteChildren: NewsletterRouteChildren = {
  NewsletterIdRoute: NewsletterIdRoute,
  NewsletterArchiveRoute: NewsletterArchiveRoute,
}

const NewsletterRouteWithChildren = NewsletterRoute._addFileChildren(
  NewsletterRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  DashboardRoute: DashboardRoute,
  ExpenseClaimsRoute: ExpenseClaimsRoute,
  LegalHubRoute: LegalHubRoute,
  LoginRoute: LoginRoute,
  ModulesRoute: ModulesRoute,
  NewsletterRoute: NewsletterRouteWithChildren,
  PermitSystemRoute: PermitSystemRoute,
  ProfileRoute: ProfileRoute,
  ResolvenAiRoute: ResolvenAiRoute,
  TasksRoute: TasksRoute,
  TravelRequestRoute: TravelRequestRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
